### PR TITLE
Add copyright to settings.gradle

### PR DESCRIPTION
**Pull request by Ab20zipYT**
**I think some devs forgot to add copyright to the settings.gradle file as done in Hyperium [here](https://github.com/HyperiumClient/Hyperium/blob/master/settings.gradle).**
I have tested it. Completely safe. Does not change anything but the appearance of the file.
Even I have used it in my project.
Trust me pls.

### CODE REVIEW

**Comment by asbyth** [comment]
1: I don't think you can license a `settings.gradle` file.
2: This file is already replaced in a local branch that I've yet to push & refer back to the first point.

**Comment by Ab20zipYT** [comment]
> 1: I don't think you can license a `settings.gradle` file.
> 2: This file is already replaced in a local branch that I've yet to push & refer back to the first point.

Why did u do that in hyperium?

**Comment by Ab20zipYT** [comment]
Bro why do u have to close all my PRs?!!

**Comment by wyvest** [comment]
> Bro why do u have to close all my PRs?!!

because the changes aren't needed, what else?

**Comment by asbyth** [comment]
> 
> 
> > 1: I don't think you can license a `settings.gradle` file.
> > 2: This file is already replaced in a local branch that I've yet to push & refer back to the first point.
> 
> Why did u do that in hyperium?

Who knows? I wasn't the one in charge of Hyperium until late 2019. Please stop commenting useless stuff as it has no reason to be here.

**Pull request closed without merging**
