### PR TITLE
Improve ChatModules, add /cr autoconfirmer, add quick WDR, clean up command & event registration

### PR DESCRIPTION
**Pull request by SirNapkin1334**
sorry that the commits are a mess

### CODE REVIEW

**Comment by SirNapkin1334** [comment]
fucks sake it added a bunch of wildcard inputs, i hate you intellij, i will fix this later

**Comment by SirNapkin1334** [comment]
IntelliJ: "Some settings are overriden by .editorconfig"
also IntelliJ: "OPTIMIZE IMPORTS??? IT'S WILDCARD TIME!!!!"

**Comment by SirNapkin1334** [comment]
Ready for merging. And before you say anythiong <@!564569026144108575> you can't retroactively make something into a draft PR, you can only convert a PR that was initially made as a draft into a regular PR.

**Comment by kazooboi** [comment]
Can you provide report types not on hypixel already and sort them into respective categories? Such as you say aimbot and the server receives killaura?

**Comment by SirNapkin1334** [comment]
Whew...I completely forgot about this. I'll probably re-do it some time. I had a reason I didn't merge it. Either way, I don't see the point in doing that. Just put in what you want yourself. There's no point in having a pre-defined list of "analagous" ones. Just say what you mean. Also, that's not the point of the command. If you take a look at the code, it allows you to type up a quicker WDR by only having to type the first letter of each thing you want to report for, GNU-options style.

**Pull request closed without merging**
