### PR TITLE
Create initial CI

### PR DESCRIPTION
**Pull request by jkroepke**
You just want to onboard/redirect the people on discord.

### CODE REVIEW

**Comment by solonovamax** [comment]
shut up lmao

**Comment by asbyth** [comment]
i've already said no, i'd rather keep it secluded to one area

**Comment by SirNapkin1334** [comment]
graincells

**Comment by jkroepke** [comment]
You dont understand how opensource development works. Sadly Sorry.

**Comment by solonovamax** [comment]
> You dont understand how opensource development works. Sadly Sorry.
They own the repo though

**Comment by FalseHonesty** [comment]
Sk1erLLC uses a different CI workflow than GitHub, so this PR will never be accepted, and re-opening the PR was non-constructive. However, I believe that it would be quite convenient to have at least on pre-release version on this repository, so I will create one. These releases may or may not continue to be posted in the future, that has yet to be determined. I would also encourage outside contributors to not spam these issues & PRs with additional non-constructive comments. Thank you all.

**Pull request closed without merging**
