### PR TITLE
new: auto chat report confirm

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**

### CODE REVIEW

**Review by proudmuslim-dev — APPROVED** [review]

**Comment by asbyth** [comment]
while im sure this would be a good addition, i cant skip the idea of people abusing this to spam chat reports faster. i may be thinking irrationally, but as of now i'm unsure, will come back to this another time

**Comment by 116s** [comment]
> while im sure this would be a good addition, i cant skip the idea of people abusing this to spam chat reports faster. i may be thinking irrationally, but as of now i'm unsure, will come back to this another time

Maybe we should add a delay to it?

**Comment by asbyth** [comment]
> Maybe we should add a delay to it?

at that point it's just faster to run the command anyway. the confirmation is there for a reason

**Comment by 116s** [comment]
> > Maybe we should add a delay to it?
> 
> at that point it's just faster to run the command anyway. the confirmation is there for a reason

Oh yes lmao

**Comment by Ab20zipYT** [comment]
I am not ban evading.

**Comment by Wyvest** [comment]
> I am not ban evading.

ok so... what does that have to do with this pull request?

**Pull request closed without merging**
