### PR TITLE
Fix formatting of imports in some files and organize HytilitiesConfig.java

### PR DESCRIPTION
**Pull request by proudmuslim-dev**
This was extremely painful and also a waste of my time

Edit: Added a TODO.md, you will probably want to modify it

### CODE REVIEW

**Comment by proudmuslim-dev** [comment]
Sorry about the absolute mess that this PR is

**Comment by FalseHonesty** [comment]
You should clean up your commits in this PR. Try to squash your commits into good commits, one for each "atomic" change. If that means squashing all into one commit, so be it. Also, good commit messages please :)

**Comment by proudmuslim-dev** [comment]
> You should clean up your commits in this PR. Try to squash your commits into good commits, one for each "atomic" change. If that means squashing all into one commit, so be it. Also, good commit messages please :)

Alright, I will. Sorry again about the mess, I think I'll delete this and redo it

**Comment by FalseHonesty** [comment]
There was no reason to close this, you can rebase your commits and force push them and make everything good again. Just google how to do it :)

**Comment by proudmuslim-dev** [comment]
I already looked up how to reword my commits and did it last night, although yeah I should've just kept this PR

**Pull request closed without merging**
