### PR TITLE
Add mod list version + Forge dependency

### PR DESCRIPTION
**Pull request by Ab20zipYT**
1) **Add mod list version:** It is better to set the mod list version so that newer versions of forge don't conflict.
2) **Forge dependency:** Depending on the Forge mod prevents players from using fake versions of Forge.

**Side-note: These changes do not affect the gameplay or anything.**

### CODE REVIEW

**Comment by wyvest** [comment]
have you tested this and made sure these changes don't stop Minecraft from loading

**Comment by asbyth** [comment]
1: `modListVersion` is completely unused in 1.8.9
2: No point, I've not once encountered someone using a "fake Forge" version

**Comment by Ab20zipYT** [comment]
I have tested it in my own mod and it does not change anything except for backend stuff.

**Comment by wyvest** [comment]
> I have tested it in my own mod and it does not change anything except for backend stuff.

yes but the backend stuff is useless, as said by asbyth

**Comment by Ab20zipYT** [comment]
> 1: `modListVersion` is completely unused in 1.8.9
> 2: No point, I've not once encountered someone using a "fake Forge" version

1. it is better to have `modListVersion`
2. "fake Forge version" means that some random dev builds a corrupted fork of forge from the repo and then a fool uses it. Depending on `mod_MinecraftForge` also allows for only clients to run the mod. Hytilities is a client-side mod, right?

**Comment by Ab20zipYT** [comment]
> > I have tested it in my own mod and it does not change anything except for backend stuff.
> 
> yes but the backend stuff is useless, as said by asbyth

Ok brothers, don't use it, I don't even care. I was just trying to help you humbly!

**Comment by asbyth** [comment]
>     1. it is better to have `modListVersion`
> 
>     2. "fake Forge version" means that some random dev builds a corrupted fork of forge from the repo and then a fool uses it. Depending on `mod_MinecraftForge` also allows for only clients to run the mod. Hytilities is a client-side mod, right?

1: Why is it better to use something that's not used once in Forge's code? They never parse this specific field.
2: They would have to change the registered modid for Forge for this to even do anything to them. People are also not going to be running Hytilities on a server.

**Pull request closed without merging**
